import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    colors: {
      'tertiary-fixed': '#ffdbcb',
      'on-secondary-container': '#b7b5b4',
      'background': '#131313',
      'surface-dim': '#131313',
      'surface-container-lowest': '#0e0e0e',
      'on-secondary': '#303030',
      'error': '#ffb4ab',
      'tertiary-container': '#ff9156',
      'surface-variant': '#353534',
      'on-tertiary-container': '#712d00',
      'on-secondary-fixed-variant': '#474746',
      'on-primary-container': '#712d00',
      'on-error-container': '#ffdad6',
      'error-container': '#93000a',
      'surface': '#131313',
      'on-secondary-fixed': '#1b1c1c',
      'inverse-surface': '#e5e2e1',
      'surface-container-low': '#1c1b1b',
      'surface-container-high': '#2a2a2a',
      'on-tertiary': '#552000',
      'on-tertiary-fixed': '#341100',
      'on-surface-variant': '#dcc1b5',
      'secondary': '#c8c6c5',
      'inverse-primary': '#9b450d',
      'inverse-on-surface': '#313030',
      'surface-container': '#201f1f',
      'on-background': '#e5e2e1',
      'on-primary': '#552000',
      'on-tertiary-fixed-variant': '#793100',
      'on-error': '#690005',
      'outline-variant': '#56433a',
      'outline': '#a48c81',
      'tertiary': '#ffba98',
      'secondary-fixed': '#e4e2e1',
      'secondary-fixed-dim': '#c8c6c5',
      'on-surface': '#e5e2e1',
      'surface-tint': '#ffb692',
      'on-primary-fixed-variant': '#793100',
      'secondary-container': '#474746',
      'primary-fixed': '#ffdbcb',
      'surface-bright': '#3a3939',
      'tertiary-fixed-dim': '#ffb692',
      'primary-fixed-dim': '#ffb692',
      'on-primary-fixed': '#341100',
      'primary': '#ffba98',
      'surface-container-highest': '#353534',
      'primary-container': '#ff9156',
      // Standard Tailwind colors needed for defaults
      'black': '#000000',
      'white': '#ffffff',
      'gray': {
        '700': '#364153',
        '800': '#1e2939',
      },
      'zinc': {
        '500': '#71717b',
        '600': '#52525c',
        '700': '#3f3f46',
      },
    },
    borderRadius: {
      'DEFAULT': '0.125rem',
      'lg': '0.25rem',
      'xl': '0.5rem',
      'full': '0.75rem',
      'md': '0.375rem',
      'sm': '0.125rem',
      '2xl': '1rem',
      '3xl': '1.5rem',
    },
    fontFamily: {
      'headline': ['Plus Jakarta Sans', 'sans-serif'],
      'display': ['Plus Jakarta Sans', 'sans-serif'],
      'body': ['Inter', 'sans-serif'],
      'label': ['Inter', 'sans-serif'],
      'sans': ['Inter', 'sans-serif'],
      'mono': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
    },
  },
  plugins: [],
} satisfies Config;
